language: c
compiler:
  - gcc
before_script:
  - sudo apt-get install gcc-avr avr-libc libelf-dev pkg-config freeglut3 freeglut3-dev scons
  - wget -O "arduino.tar.gz" "http://arduino.googlecode.com/files/arduino-1.0.5-linux64.tgz"
  - tar xzf arduino.tar.gz
script: scons ARDUINO_BOARD=uno ARDUINO_HOME="$(pwd)/arduino-1.0.5"
